version: '3.0'
services:
  database:
    image: amsterdam/postgres11
#    ports:
#      - "5406:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: handelsregister
      POSTGRES_USER: handelsregister
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - tmpdatabase:/tmp
      - ./pgdata:/var/lib/postgresql/data
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  elasticsearch:
    image: amsterdam/elasticsearch6
    command:  elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: ./web
    ports:
      - "8102:8080"
    links:
      - database
      - elasticsearch
    volumes:
      - $PWD/data:/app/data
    environment:
      DATABASE_NAME: handelsregister
      DATABASE_USER: handelsregister
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      PGPASSWORD: insecure
      UWSGI_HTTP: ":8080"
      UWSGI_MODULE: "handelsregister.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/handelsregister/static=/static"
      UWSGI_OFFLOAD_THREADS: 1
      UWSGI_VACUUM: 1
      UWSGI_HARAKIRI: 15
      UWSGI_DIE_ON_TERM: 1
      command: bash /app/docker-run.sh

#  swaggerui:
#    image: amsterdam/oauth2swaggerui
#    ports:
#      - 8686:8686

volumes:
   tmpdatabase:
