database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: handelsregister

tests:
  build: ../web
  links:
    - database:database
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_USER: handelsregister
    DATABASE_PASSWORD: insecure
  command: /app/docker-test.sh


importer:
  build: ../web
  links:
    - database:database
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_USER: handelsregister
    DATABASE_PASSWORD: insecure
    OS_PASSWORD:
    PGPASSWORD: insecure
  command: >
    bash -c "/app/docker-import.sh"

db-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database:db
  environment:
    PGPASSWORD: insecure
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo database:5432:handelsregister:handelsregister:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -t hr* \
                        -t kvk* \
                        -t geo*  \
                        -T auth*    \
                        -U handelsregister \
                        -h db -p 5432 \
                        handelsregister > /tmp/backups/database.dump"
            && chown -R 997:997 /tmp/backups"
