
database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: handelsregister

elasticsearch:
  image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch
  volumes:
    - ./backups/elasticsearch:/tmp/backups
  user: root
  command: /usr/share/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -Des.network.host=0.0.0.0 -Des.path.repo=/tmp

tests:
  build: ../web
  links:
    - database:database
  volumes:
    - ../reports:/app/reports
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_USER: handelsregister
    DATABASE_PASSWORD: insecure
  command: bash -c "/app/docker-wait.sh && python manage.py jenkins"

importer_mks:
  build: ../web
  links:
    - database:database
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_PASSWORD: insecure
    PGPASSWORD: insecure
    OS_PASSWORD:
  command: >
    bash -c "/app/docker-wait.sh \
            && yes \"yes\" | python manage.py migrate \
            && python load_mks_dumps.py \
            && bash -c /app/loaddumps.sh"

importer_1:
  build: ../web
  links:
    - database:database
    - elasticsearch:elasticsearch
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_PASSWORD: insecure
  volumes:
    - ./data:/app/data
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py run_import --partial 1/3"

importer_2:
  build: ../web
  links:
    - database:database
    - elasticsearch:elasticsearch
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_PASSWORD: insecure
  volumes:
    - ./data:/app/data
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py run_import --partial 2/3"


importer_3:
  build: ../web
  links:
    - database:database
    - elasticsearch:elasticsearch
  environment:
    DATABASE_NAME: handelsregister
    DATABASE_PASSWORD: insecure
  volumes:
    - ../data:/app/data
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py run_import --partial 3/3"


db-backup:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database:db
  environment:
    PGPASSWORD: insecure
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo database:5432:handelsregister:handelsregister:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -t hr* \
                        -t kvk* \
                        -t geo*  \
                        -T auth*    \
                        -U handelsregister \
                        -h db -p 5432 \
                        handelsregister > /tmp/backups/database.dump"
